server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true

spring:
  ai:
    ollama:
      base-url: http://localhost:11434/
      chat:
        model: qwen2:0.5b
  threads:
    virtual:
      enabled: true
  config:
    import:
      - secret.yml
  profiles:
    active:
      - local
  application:
    name: free-webui

logging:
  config: classpath:logback-free.xml

---

server:
  config:
    activate:
      on-profile:
        - local

spring:
  config:
    activate:
      on-profile:
        - local
    import:
      - secret.yml

  devtools:
    livereload:
      enabled: true
    restart:
      poll-interval: 2s
      enabled: true


---

server:
  port: 8080
  config:
    activate:
      on-profile:
        - prod

spring:

  config:
    activate:
      on-profile:
        - prod
    import:
      - secret.yml
