server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true

spring:

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        globally_quoted_identifiers: true #DB ???? ??
        default_batch_fetch_size: 1000
        format_sql: true
        use_sql_comments: true
        show_sql: false

  devtools:
    livereload:
      enabled: true
    restart:
      poll-interval: 5s
      enabled: false

  h2:
    console:
      enabled: true


  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/spring-ai-chat-db;MODE=MYSQL
    username: sa
    password:

  ai:
    ollama:
      base-url: http://localhost:11434/
      chat:
        options:
          top-k:
#      chat:
#        model: qwen2:0.5b

  threads:
    virtual:
      enabled: true
  profiles:
    active:
      - local
  application:
    name: free-webui

logging:
  config: classpath:logback-free.xml

---

server:
  config:
    activate:
      on-profile:
        - local

spring:
  config:
    activate:
      on-profile:
        - local



---

server:
  port: 8080
  config:
    activate:
      on-profile:
        - prod

spring:

  config:
    activate:
      on-profile:
        - prod
