server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true


spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        globally_quoted_identifiers: true #DB ???? ??
        default_batch_fetch_size: 1000
        format_sql: true
        use_sql_comments: true
        show_sql: false

  devtools:
    livereload:
      enabled: true
    restart:
      poll-interval: 5s
      enabled: false

  h2:
    console:
      enabled: true


  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/spring-ai-chat-db;MODE=MYSQL
    username: sa
    password:

  ai:
    ollama:
      base-url: http://localhost:11434/
      embedding:
        model: nomic-embed-text
      init:
        pull-model-strategy: when_missing
        timeout: 60s
        max-retries: 1
      chat:
        model: qwen2.5-coder:7b
    chat:
      client:
        enabled: false


  threads:
    virtual:
      enabled: true
  profiles:
    active:
      - local
  application:
    name: free-webui
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

logging:
  config: classpath:logback-free.xml
gg:
  jte:
    templateLocation: src/main/jte
    templateSuffix: .jte
    developmentMode: true

---

server:
  config:
    activate:
      on-profile:
        - local

spring:
  config:
    activate:
      on-profile:
        - local



---

server:
  port: 8080
  config:
    activate:
      on-profile:
        - docker

spring:

  config:
    activate:
      on-profile:
        - docker
  ai:
    ollama:
      base-url: http://host.docker.internal:11434/
gg:
  jte:
    usePrecompiledTemplates: true
    developmentMode: false
